Spring:
  application:
    name: university

  datasource:
    url: jdbc:postgresql://localhost:5434/Dev
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        format_sql: true
      show_sql: true
      open-in-view: false
